Remind_Player: true # If the player has an existing quiz, a reminder will be sent to them every X minute
Remind_Interval: 3 # In minutes;

soundOnCorrectAnswer: "BLOCK_NOTE_BLOCK_CHIME"
soundOnWrongAnswer: "BLOCK_NOTE_BLOCK_DIDGERIDOO"
soundOnCompleted: "ENTITY_PLAYER_LEVELUP"

Chat_Question_Format:
  - "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃" # Header
  - "&6{question}" # The question
  - "" # Space
  - "&e- {choices}" # The choice prefix, choices will be in 4 lines
  - "" # Space
  - "▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃" # Footer

notTaken:
  Title: "&6{categoryTitle}"
  Item: "BOOK"
  Lore:
    - "&eStatus: Available"
    - "&eNumber of Questions: {total}"
    - "&eMinimum Passing Score: {passing}"
Completed:
  Title: "&6{categoryTitle}"
  Item: "LIME_CONCRETE"
  Lore:
    - "&eStatus: Completed"
    - "&eNumber of Questions: {total}"
    - "&eMinimum Passing Score: {passing}"
prequisiteRequired:
  Title: "&6{categoryTitle}"
  Item: "RED_CONCRETE"
  Lore:
    - "&eStatus: Unavailable"
    - "&eNumber of Questions: {total}"
    - "&eMinimum Passing Score: {passing}"
    - ""
    - "&eRequirement to access"
    - "&d{requiredCategoryTitle}"
noPermission:
  Title: "&6{categoryTitle}"
  Item: "BARRIER"
  Lore:
    - "&eProgress /journals to access this!"